### ISSUE TITLE
Retrieving Answer... (then nothing)

### ISSUE THREAD

**Issue by pkkid** [jlangston/SublimeHowDoI#3]
I often get what I can only imagine is a timeout error of some sort.  It seems often times when I query the status bar will show the "Retrieving answer..." text, but then nothing happens.  If I try the same query on the command line with the "howdoi" script, I get the answer.

This is intermittent.  Usually after a few successful queries in Sublime Text it will start to fail more often.

**Comment by jlangston** [comment]
Do you get any particular error message in the sublime text console when this happens?

**Comment by pkkid** [comment]
I forgot this was opened.  In any event, I eventually figured out this was my own doing.
Sorry for the noise.

**Comment by pepkin88** [comment]
I had the following error:

```
Exception in thread Thread-41:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "SublimeHowDoI in C:\Users\Marek\AppData\Roaming\Sublime Text 3\Installed Packages\How Do I Code Search.sublime-package", line 54, in run
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 13: invalid start byte
```

Sublime Text 3, build 3083 on Windows 8.1 x64. I installed the package from Package Control.
